# .air.toml
[build]
cmd = "go build -o ./tmp/main ./cmd/api/main.go"
bin = "tmp/main"
full_bin = "tmp/main"
exclude_dir = ["tmp", "vendor"]
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_file = []
delay = 1000
stop_on_error = true

[log]
time = true
