services:
  app:
    build:
      dockerfile: ./docker/go/Dockerfile
      context: .
    container_name: echo_app
    ports:
      - ${APP_PORT:-8080}:8080
    depends_on:
      - mysql
      - redis
    env_file:
      - path: .env
    environment:
      - MYSQL_DSN=user:password@tcp(mysql:3306)/dbname?charset=utf8mb4&parseTime=True&loc=Local
      - REDIS_ADDR=redis:6379

  mysql:
    image: mysql:8.0
    container_name: mysql8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_HOST_PORT:-3306}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-3306}
      MYSQL_USER: ${MYSQL_USER:-3306}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-3306}
    ports:
      - ${MYSQL_HOST_PORT:-3306}:3306
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - ${REDIS_HOST_PORT:-6379}:6379
    volumes:
      - redis-data:/data

volumes:
  mysql-data:
  redis-data: